config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # line from command line 'rails g device User '
  devise_for :users

=begin
  - this line makes all of the routes for us
  - BUT still need to define our root (unless we want default)
  - instead of having all the individual get, patch, etc lines (see early commits before part 8 or 9)
=end
  resources :blog_posts




  # Defines the root path route ("/")
  # index action will display all of the blog posts
  root "blog_posts#index" 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog_post.rb
class BlogPost < ApplicationRecord
    # ensure that the new title and the new body are not empty
    validates :title, presence: true
    validates :body, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, #:registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blog_posts_controller.rb
# inherit from application controller aka action controller
# the controller gives us the info we need to process HTTP requests like parameters
    # and appropriate responses
class BlogPostsController < ApplicationController 

    # from devise package to authenticate user
    # only allows users to see index and show if not logged in 
    before_action :authenticate_user!, except: [:index, :show]

=begin refactoring 1/2
    - set_blog_post allows us reduce the num of lines in code
    - before: the methods show, edit, update, etc all had the same line to set blog action
    - now: line 11 only and the set_blog_action method
    - could also define before action with except: instead of only
=end 
    before_action :set_blog_post, only: [:show, :edit, :update, :destroy]


    # from devise package to authenticate user
    before_action :authenticate_user!, except: [:index, :show]


    def index
        # instance variable to ensure we share with index.html.erb to render
        @blog_posts = BlogPost.all
    end

    def show
        # rescue that used to be here was moved to set_blog_post
    end

    def new 
        #create new blog post in memory
        @blog_post = BlogPost.new
    end

    # create and save the new blog post
    def create
        @blog_post = BlogPost.new(blog_post_params)
        if @blog_post.save
            redirect_to @blog_post
        else
            # rendering the new.html.erb instead of making a create.html.erb
            # unprocessable_entity gives 422 error instead of 200 ok
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        # calls on before_action
    end

    def update
        # find the id again, instead of creating brand new post
        if @blog_post.update(blog_post_params) # use same title and body params
            redirect_to @blog_post
        else 
            render :edit, status: :unprocessable_entity
        end
    end

    # don't need if/else bc we assume that destroy is successful
    # then redirect to root path cause blog post doesn't exist anymore
    def destroy
        @blog_post.destroy
        redirect_to root_path
    end

    # want private to ensure security
    private

    def blog_post_params
        params.require(:blog_post).permit(:title, :body)
    end


    # refactoring 2/2
    def set_blog_post
        @blog_post = BlogPost.find(params[:id])
    rescue ActiveRecord::RecordNotFound # used to be in show, 
        #but it's optional depending on application
        redirect_to root_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/blog_posts/_form.html.erb
<%# underscore indicates that this is a partion - portion of a page%>

<%= form_with model: @blog_post do |form| %>
    <%# handling cases where the new blog post is filled out incorrectly%>
    <%# good to have form.object instead of form.blog post in case there are name changes%>
        <%# you won't have to modify everything in the if statement%>
    <% if form.object.errors.any? %>
        <div>            
            <% form.object.errors.full_messages.each do |message| %>
                <div><%= message %></div>
            <% end %>
            
        </div> 
    <% end %>

    <%# the new blog post 'form'%>
    <div>
        <%= form.label :title %>
        <%= form.text_field :title %> <%# single string%>
    </div>

    <div>
        <%= form.label :body %>
        <%= form.text_area :body %> <%# multi line strings%>
    </div>

    <%= form.button %>
<% end %>

app/views/blog_posts/edit.html.erb
<h1>Edit blog post</h1>

<%# rendering the partial again like in new.html.erb%>
<%= render partial: "form", locals: {blog_post: @blog_post} %>

<%# adding delete button in the edit page
    keeping the path ambigious again - rails figures it out 
    
    turbo javascript - automatically comes with rails 7 - it will ask for ok/cancel with string
    See /app/javascript/application.js - there is a line where hotwired/turbo is imported%>
<%= button_to "Delete", @blog_post, method: :delete, data: {turbo_confirm: "Are you sure?"}%>

app/views/blog_posts/index.html.erb
<h1>My Blog</h1>

<% @blog_posts.each do |blog_post| %>
    <div>
        <%# ruby can figure out the path on it's own cause of the object%>
        <%# remember the = is for .erb formatting%>

        <h2><%= link_to blog_post.title, blog_post%></h2>
        <%= blog_post.body %>
    </div>
<% end %>

app/views/blog_posts/new.html.erb
<h1> New Blog Post </h1>


<%# rendering the _form partial %>
<%= render partial: "form", locals: {blog_post: @blog_post} %>

app/views/blog_posts/show.html.erb
<%= link_to "Edit", edit_blog_post_path(@blog_post) if user_signed in? %>
<h1><%= @blog_post.title%></h1>
<%= @blog_post.body%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="prose mx-auto">
    <%# class notice and alert from command line 'rails g devise:install
      these are for if a user logs in or fails to log in, there will be a notice%>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div>
      <% if user_signed_in? %>
        <%= link_to "New blog post", new_blog_post_path %>
        <%# edit user registration, destroy, etc all from devise 
          - commenting out the link to profile cause we will log in with rails c%>
        <%#= link_to "Profile", edit_user_registration_path %>
        <%= button_to "Log out", destroy_user_session_path, method: :delete %>
      <%# commenting the else portion out because we removed the registerable line is user.rb model
        - don't want anyone to be able to sign up and log into our blog
        - we only want just us (admin) to be able to login and edit blogs %>
      <%# else %>
        <%#= link_to "Login", new_user_session_path %>
        <%#= link_to "Sign Up", new_user_registration_path %>

      <% end %>
    </div>

    <%= yield %>
  </body>
</html>